import { lazy } from "react";

const uiLazy = (path) => lazy(() => import(`./ui/${path}.jsx`));
export const HomePage = lazy(() => import("@/components/HomePage"));
export const NavBar = lazy(() => import("@/components/Navbar"));
export const BuilderPage = lazy(() => import("@/components/BuilderPage"));
export const CheckerPage = lazy(() => import("@/components/CheckerPage"));
export const ResultsColumn = uiLazy("ResultsColumn");
export const ModernTemplate = uiLazy("ModernTemplate");
export const ProfessionalTemplate = uiLazy("ProfessionalTemplate");
export const InputColumn = uiLazy("InputColumn");
export const BuildPageHeader = uiLazy("BuildPageHeader");
export const MobileTabToggle = uiLazy("MobileTabToggle");
export const HeroSection = uiLazy("HeroSection");
export const FeatureHighlights = uiLazy("FeatureHighlights");
export const FeatureCard = uiLazy("FeatureCard");
export const Input = uiLazy("Input");
export const Textarea = uiLazy("Textarea");
export const ResumeForm = uiLazy("ResumeForm");
export const ResumePreview = uiLazy("ResumePreview");
export const ResumeInputPanel = uiLazy("ResumeInputPanel");
export const JobDescriptionPanel = uiLazy("JobDescriptionPanel");
export const RoleSelector = uiLazy("RoleSelector");
export const ATSResults = uiLazy("ATSResults");
export const ScoreCard = uiLazy("ScoreCard");
export const ScoreBreakdown = uiLazy("ScoreBreakdown");
export const KeywordMatchPanel = uiLazy("KeywordMatchPanel");
export const MissingSectionsPanel = uiLazy("MissingSectionsPanel");
export const SuggestionsPanel = uiLazy("SuggestionsPanel");
export const ContactItem = uiLazy("ContactItem");
export const DynamicSection = uiLazy("FormSections");
