import { lazy } from "react";

export const HomePage = lazy(() => import("./pages/HomePage"));
export const NavBar = lazy(() => import("./Navbar"));
export const BuilderPage = lazy(() => import("./pages/BuilderPage"));
export const CheckerPage = lazy(() => import("./pages/CheckerPage"));
export const FeatureCard = lazy(() => import("./modules/builder/components/common/FeatureCard"));
export const Input = lazy(() => import("./modules/builder/components/common/Input"));
export const Textarea = lazy(() => import("./modules/builder/components/common/Textarea"));
export const ModernTemplate = lazy(() => import("./modules/builder/templates/ModernTemplate"));
export const ProfessionalTemplate = lazy(() => import("./modules/builder/templates/ProfessionalTemplate"));
export const ResumeForm = lazy(() => import("./modules/builder/ResumeForm"));
export const ResumePreview = lazy(() => import("./modules/builder/ResumePreview"));
export const Layout = lazy(() => import("./Layout"));
export const DynamicSection = lazy(() => import("./modules/builder/FormSections"),);
export const ResumeInputPanel = lazy(() => import("./modules/ats-checker/components/ResumeInputPanel"),);
export const JobDescriptionPanel = lazy(() => import("./modules/ats-checker/components/JobDescriptionPanel"),);
export const RoleSelector = lazy(() => import("./modules/ats-checker/components/RoleSelector"),);
export const ATSResults = lazy(() => import("./modules/ats-checker/components/ATSResults"),);
export const ScoreCard = lazy(() => import("./modules/ats-checker/components/ScoreCard"),);
export const ScoreBreakdown = lazy(() => import("./modules/ats-checker/components/ScoreBreakdown"),);
export const KeywordMatchPanel = lazy(() => import("./modules/ats-checker/components/KeywordMatchPanel"),);
export const MissingSectionsPanel = lazy(() => import("./modules/ats-checker/components/MissingSectionsPanel"),);
export const SuggestionsPanel = lazy(() => import("./modules/ats-checker/components/SuggestionsPanel"),);
export const ContactItem = lazy(() => import("./modules/builder/components/common/ContactItem"),);
// Helper for lazy loading named exports
const lazyIcon = (name) => lazy(() => import("./CustomIcons").then(module => ({ default: module[name] })));

// icons
export const UserIcon = lazyIcon("UserIcon");
export const HomeIcon = lazyIcon("HomeIcon");
export const FileTextIcon = lazyIcon("FileTextIcon");
export const CpuIcon = lazyIcon("CpuIcon");
export const LayoutIcon = lazyIcon("LayoutIcon");
export const MoonIcon = lazyIcon("MoonIcon");
export const SunIcon = lazyIcon("SunIcon");
export const Edit3Icon = lazyIcon("Edit3Icon");
export const TrashIcon = lazyIcon("TrashIcon");
export const DownloadIcon = lazyIcon("DownloadIcon");
export const EyeIcon = lazyIcon("EyeIcon");
export const ResumeIcon = lazyIcon("ResumeIcon");
export const BriefcaseIcon = lazyIcon("BriefcaseIcon");
export const SparklesIcon = lazyIcon("SparklesIcon");
export const AwardIcon = lazyIcon("AwardIcon");
export const CheckCircle2Icon = lazyIcon("CheckCircle2Icon");
export const AlertCircleIcon = lazyIcon("AlertCircleIcon");
export const TrendingUpIcon = lazyIcon("TrendingUpIcon");
export const MapPinIcon = lazyIcon("MapPinIcon");
export const StarIcon = lazyIcon("StarIcon");
export const PhoneIcon = lazyIcon("PhoneIcon");
export const MailIcon = lazyIcon("MailIcon");
export const PlusIcon = lazyIcon("PlusIcon");
export const GraduationCapIcon = lazyIcon("GraduationCapIcon");
export const CodeIcon = lazyIcon("CodeIcon");
export const SearchIcon = lazyIcon("SearchIcon");
