// Icons — eagerly exported since CustomIcons.jsx is only ~14KB
// and these icons are used across the entire app. Individual lazy loading
// of 25 icons creates unnecessary chunk overhead.
export {
  UserIcon,
  HomeIcon,
  FileTextIcon,
  CpuIcon,
  LayoutIcon,
  MoonIcon,
  SunIcon,
  Edit3Icon,
  TrashIcon,
  DownloadIcon,
  EyeIcon,
  ResumeIcon,
  BriefcaseIcon,
  SparklesIcon,
  AwardIcon,
  CheckCircle2Icon,
  AlertCircleIcon,
  TrendingUpIcon,
  MapPinIcon,
  PhoneIcon,
  MailIcon,
  PlusIcon,
  GraduationCapIcon,
  CodeIcon,
  SearchIcon,
} from "./CustomIcons";
